### PR TITLE
Cross cuts

### PR DESCRIPTION
**Pull request by mbaudin47**
This creates cross-cuts for functions, distributions and events.

* The CrossCutFunction is presented in https://github.com/mbaudin47/otbenchmark/blob/CrossCuts/examples/CrossCutFunction_Demo.ipynb
* The theory of ConditionalDistribution is presented in https://github.com/mbaudin47/otbenchmark/blob/CrossCuts/examples/ConditionalDistribution_Theory.ipynb and a demo in https://github.com/mbaudin47/otbenchmark/blob/CrossCuts/examples/ConditionalDistribution_Demo.ipynb. 
* The CrossCutDistribution is in https://github.com/mbaudin47/otbenchmark/blob/CrossCuts/examples/CrossCutDistribution-3D_Demo.ipynb
* The DrawEvent demo is in https://github.com/mbaudin47/otbenchmark/blob/CrossCuts/examples/DrawEvent_demo.ipynb
* A full demo of these cross-cuts is in https://github.com/mbaudin47/otbenchmark/blob/CrossCuts/examples/draw-cross-cuts.ipynb
* The application to RP8 is in https://github.com/mbaudin47/otbenchmark/blob/CrossCuts/examples/RP8_Demo.ipynb

### CODE REVIEW

**Comment by mbaudin47** [comment]
@vchabri, @efekhari27 : Please review this PR.

**Comment by vchabri** [comment]
Great work! Thanks Michael.
Here are a few comments about each document:

1. [CrossCutFunction_Demo.ipynb]:
- For the last cell with the various figures (A, b, C, D, E, F), I don't get the reason why Figs. D and E show contours which are orthogonal to the ones presented here (https://rprepo.readthedocs.io/en/latest/reliability_problems.html#rp33). If the gradient follows a given stepwise direction (e.g., from left to right), why in these plots it is from bottom to top?
- Nice explanation at the end of the Notebook!!! Just a question: would it be possible to use/create a method like ".getDesignPoint()" in the X-space or in the U-space as a reference point?

2. [ConditionalDistribution_Theory.ipynb]:
- The theory reminders are clear and well-explained. However, there are a few typos in the text ("and", "integeger", typo in the equation f_{X|Xc}).

3. [ConditionalDistribution_Demo.ipynb]:
- Nice example. Maybe I could help to provide a few more examples (issued from my PhD manuscript or other resources).

4. [DrawEvent_demo.ipynb]:
- Really nice. I got the same question as previously. What is missing in the code to draw similar graphs from a reference point taken as the design point P* ?

5. [RP8_Demo.ipynb]:
- Amazing!! Question: Is it the white square in the plots (e.g., top left, or top right) the "removed legend" ?
- For the other sets of plots, I would suggest to add a marker to the reference point as it is not that clear on the plots.

Hope these remarks will help. The work is great!

**Comment by mbaudin47** [comment]
* [CrossCutFunction_Demo.ipynb] There is a bug in the x1, x2 projection. Either the RP or myself is wrong. 
* Reference point from design point. It will be possible to draw the function in the X-space. In the U-space, it will be possible by composition of the probabilistic transformation and the function itself. This would be very nice example indeed.

**Comment by mbaudin47** [comment]
This development is not completely finished, but the current version runs fine and provides interesting features. This is why I merge it.

**Pull request merged**
