### PR TITLE
Fixed RP14. Renamed methods. Fixes #7: method names were too long.

### LINKED ISSUE #7: The class names are way too long.
* RminusSReliabilityBenchmarkProblem > RminusSReliability
* FourBranchSerialSystemReliabilityBenchmarkProblem > FourBranchSerialSystemReliability
* IshigamiSensitivityBenchmarkProblem > IshigamiSensitivity
* AxialStressedBeamReliabilityBenchmarkProblem > AxialStressedBeamReliability

### PR DESCRIPTION
**Pull request by mbaudin47**
* Fixed RP14. The formula had two bugs. The exact parametrization of Gumbel is from mean and standard deviation. Created the missing unit test to really check the pf.
* Renamed methods.
* Fixes #7: method names were too long.

### CODE REVIEW

**Comment by mbaudin47** [comment]
@JEBROUN : does it seem correct to you?

**Comment by mbaudin47** [comment]
@JEBROUN : is the PR correct up to you?

**Comment by JEBROUN** [comment]
excuse me, I have not seen this PR, yes, it seems correct

**Comment by JEBROUN** [comment]
Indeed, I still found a problem with RP14, thanks for your corrections !

**Pull request merged**
