### PR TITLE
exact probability

### PR DESCRIPTION
**Pull request by JEBROUN**

### CODE REVIEW

**Comment by mbaudin47** [comment]
Hi Youssef,
I cannot find the script where you computed the reference probability of each problem based on Monte-Carlo sampling with sample size equal to 10**9 with CV=0.1. Can you point where this is?

I ask this because I guess that this reference value may be improved for some of the test cases. For example, the reference probability for RP53 is 3.3e-2 (while BBRC stated 3.13e-2). However, because this probability is not so close to zero, the reference probability may be computed more accurately, setting the CV to zero. This would allow to actually consume the 10**9 budget instead of stopping on the CV criteria. This would reduce the confidence interval and perhaps get 1 or 2 more accurate digits on this case. @vchabri, @efekhari: do you agree?

**Comment by JEBROUN** [comment]
Hi @mbaudin47 !!

Here you will find the two scripts I used to generate the exact probabilities.

**Comment by mbaudin47** [comment]
Great, thanks. I will look at it in detail and let you know if this fits.

**Comment by efekhari27** [comment]
Hi @mbaudin47,
We discussed this exact issue a few weeks ago with @vchabri and @JEBROUN. Like you mentioned, for some problems the cv = 0.1 criterion is reached before consuming the 10**9 CMC iteration budget and it would be great to have more accuracy. Some problems really deserve to be investigated to understand the gaps between the BBRC, ComputeCDF(0) and OT CMC (if i'm not mistaken RP28 is a good example).
Best,
Elias

**Comment by efekhari27** [comment]
Hi again all, 

I took a look at the two new files and i have a few questions/remarks: 
- What is the difference between the two of them?
- Why is the OTReliabillityAlgorithmBenchmark used since the Factories were developed? Shouldn't this class be deprecated?
- Why is the blockSize set at such a small value?
- The values should appear completely in the DataFrame if it is used.
- The cv should also be displayed in the table.
-  The end of the Monte Carlo sampling should have a more complex rule as @mbaudin47 said. I don't know how to do it but it should be a logic condition like 
```
coefficientOfVariation <= 0.1 and maximumOuterSampling >= 10**9
```

Best, 
Elias

**Comment by mbaudin47** [comment]
My way to solve this would be:
```
maximumOuterSampling = 10**9
```
whatever the value of the CV. Indeed, what we want is to "get the most possible accuracy", not "have a sufficient accuracy". In order to do this, I suggest to use `CV=0.0` and see if the benchmark can be run within a reasonable amount of time.

When storing the result into the script, only accurate digits should be written. For example, we may get "pf=1.23456789e-7" from Monte-Carlo, but write "pexact=1.234e-7" if only 4 significant digits are known.

In order to know what is the number of correct digits, I have two approaches in mind.
* The number of "probabilistic" decimal digits may be computed from the CV, with d = -log10(CV). I have no rigorous mathematical proof for this yet in the probabilistic setting, but I guess that this is the short answer that could be given a mathematical sense. In a deterministic setting, this would correspond to the Log-Relative Error (I have a rigorous proof for this).
* We may compute a 95% confidence interval, and see which digits are common in the lower and upper bounds. For example, if the C.I. is [1.23456e-4, 1.23478e-4], then the reference value would be 1.234e-4 with only 4 correct digits.

**Comment by mbaudin47** [comment]
I could not see the difference between Results/Fichier_proba_exacte.ipynb and Results/Fichier_proba_reference.ipynb. Is there any significant difference?
In order to see the behaviour with really large samples, I created the following bench, which seems to reveal more digits:

https://github.com/mbaudin47/otbenchmark/blob/FixUT/examples/reliability_compute_reference_proba.ipynb

However, this does not tell the whole story. 
* RP55 (pf=5.60e-01), the easiest, only has 2 digits correct. Another method should be used to get full accuracy (FORM ?).
* RP63 (100 dimensions) seems to cost more than required. Would a Python implementation be faster?
* RP28 (pf=3.e-7) has no digit. Would SORM perform better.

In all cases, other method could be used:
* computeCDF() : see where it works, where it does not work,
* FORM-IS to be compared to plain MC,
* Quasi-Monte-Carlo to improved speed, if possible.

**Comment by mbaudin47** [comment]
This PR does not actually improve the accuracy, because the reference probabilities were not computed with large enough samples. The tables for each problem are integrated in the examples in PR #55. The algorithm factories are also included in master, with improvements. This is why I close the current PR.

**Pull request closed without merging**
